LENGTH_NAME = 150
LENGTH_EMAIL = 254

DEFAULT_PAGE_SIZE = 6

COOKING_MIN_TIME = 1
INGREDIENT_MIN_AMOUNT = 1
RECIPE_LENGTH = 256
INGREDIENT_LENGTH = 128
MEASUREMENT_LENGTH = 64
TAG_NAME = 32
SHORT_LINK_LENGTH = 128

RESTRICTED_USERNAME = ['me', 'set_password', 'subscriptions']
