LENGTH_NAME = 150

DEFAULT_PAGE_SIZE = 6

COOKING_MIN_TIME = 1
COOKING_MAX_TIME = 32000
INGREDIENT_MIN_AMOUNT = 1
INGREDIENT_MAX_AMOUNT = 32000
RECIPE_LENGTH = 256
INGREDIENT_LENGTH = 128
MEASUREMENT_LENGTH = 64
TAG_NAME = 32
SHORT_LINK_CODE_LENGTH = 6

RESTRICTED_USERNAME = ['me', 'set_password', 'subscriptions']
